# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: TylerHong.OpenTypeless
PackageVersion: 1.4.2
MinimumOSVersion: 10.0.19041.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: OpenTypeless_is1
AppsAndFeaturesEntries:
- DisplayName: OpenTypeless
  Publisher: TylerHong
  ProductCode: OpenTypeless_is1
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Tyler913/OpenTypeless/releases/download/1.4.2/OpenTypeless-1.4.2-windows-x64-setup.exe
  InstallerSha256: 39AD4C73072506F39380C97976B9D60EE549B263525B92B4528F2A258E71775C
- Architecture: arm64
  InstallerUrl: https://github.com/Tyler913/OpenTypeless/releases/download/1.4.2/OpenTypeless-1.4.2-windows-arm64-setup.exe
  InstallerSha256: 8E31E98B17D112E1590056EB53EA364F145712878B6C9709DA8683F9DA68C760
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-10-02
